CREATE INDEX ix_asset_codes_code ON asset_codes(code);
CREATE INDEX ix_attachments_facility_id ON attachments(facility_id);
CREATE INDEX ix_attachments_sku_id ON attachments(sku_id);
CREATE INDEX ix_inventories_facility_id_sku_id ON inventories(facility_id, sku_id);
CREATE INDEX ix_facilities_published_delivery_radius ON facilities(published, delivery_radius);
CREATE INDEX ix_facilities_alternate_phone_number ON facilities(alternate_phone_number);
CREATE INDEX ix_facilities_creator ON facilities(creator_id);
CREATE INDEX ix_facilities_phone_number ON facilities(phone_number);
CREATE INDEX ix_facilities_min_max_lat_lng ON facilities(min_lat, max_lat, min_lng, max_lng);
CREATE INDEX ix_facilities_lat_lng ON facilities(lat, lng);
CREATE INDEX ix_order_addresses_order_id ON order_addresses(order_id);
CREATE INDEX ix_order_lines_order_id ON order_lines(order_id);
CREATE INDEX ix_order_statuses_order_id ON order_statuses(order_id);
CREATE INDEX ix_order_attributes_order_id ON order_attributes(order_id);
CREATE INDEX ix_orders_parent_order_id ON orders(parent_order_id);
CREATE INDEX ix_items_asset_code_id ON items(asset_code_id);
CREATE UNIQUE INDEX ix_index_directories_name ON index_directories(name);
CREATE INDEX ix_index_files_name ON index_files(index_directory_id,name);
